<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.XEmVuWg' shared service.

return $this->privates['.service_locator.XEmVuWg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ApiController::ajout' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\ApiController::superadmin' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ApiController:ajout' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\ApiController:superadmin' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
], [
    'App\\Controller\\ApiController::ajout' => '?',
    'App\\Controller\\ApiController::superadmin' => '?',
    'App\\Controller\\ApiController:ajout' => '?',
    'App\\Controller\\ApiController:superadmin' => '?',
]);
