<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAcqAix2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAcqAix2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAcqAix2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAcqAix2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAcqAix2\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AcqAix2',
    'container.build_id' => '2d925823',
    'container.build_time' => 1563953051,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAcqAix2');
