<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5utCsrZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5utCsrZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5utCsrZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5utCsrZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container5utCsrZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '5utCsrZ',
    'container.build_id' => '9c881719',
    'container.build_time' => 1564088208,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5utCsrZ');
