<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYOD2EUY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYOD2EUY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYOD2EUY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYOD2EUY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYOD2EUY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YOD2EUY',
    'container.build_id' => 'bf4d5fac',
    'container.build_time' => 1563967094,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYOD2EUY');
